// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rGTIQs-BVDtzUgfFT1jFhLdamNRfaSI',
    appId: '1:323150359622:web:0ba081be5ca07cb7c2ae47',
    messagingSenderId: '323150359622',
    projectId: 'hethongbaochay-56774',
    authDomain: 'hethongbaochay-56774.firebaseapp.com',
    storageBucket: 'hethongbaochay-56774.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rGTIQs-BVDtzUgfFT1jFhLdamNRfaSI',
    appId: '1:323150359622:android:0ba081be5ca07cb7c2ae47c2ae47',
    messagingSenderId: '323150359622',
    projectId: 'hethongbaochay-56774',
    authDomain: 'hethongbaochay-56774.firebaseapp.com',
    storageBucket: 'hethongbaochay-56774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-rGTIQs-BVDtzUgfFT1jFhLdamNRfaSI',
    appId: '1:323150359622:ios:0ba081be5ca07cb7c2ae47c2ae47',
    messagingSenderId: '323150359622',
    projectId: 'hethongbaochay-56774',
    authDomain: 'hethongbaochay-56774.firebaseapp.com',
    storageBucket: 'hethongbaochay-56774.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-rGTIQs-BVDtzUgfFT1jFhLdamNRfaSI',
    appId: '1:323150359622:ios:0ba081be5ca07cb7c2ae47c2ae47',
    messagingSenderId: '323150359622',
    projectId: 'hethongbaochay-56774',
    authDomain: 'hethongbaochay-56774.firebaseapp.com',
    storageBucket: 'hethongbaochay-56774.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
